site_name: Учебник Биологии
theme:
  name: material
  language: ru
  palette: 
    scheme: default # Светлая тема (лучше для чтения сканов)
  features:
    - navigation.top
    - navigation.tracking

nav:
  - Читать учебник: index.md
